#!/usr/bin/python
# Copyright Douglas Squirrel 2011
# This program comes with ABSOLUTELY NO WARRANTY. 
# It is free software, and you are welcome to redistribute it under certain conditions; see the GPLv3 license in the file LICENSE for details.

import glob, messageboard, os.path, sys, subprocess

def basename_without_extension(file_path):
    return os.path.splitext(os.path.basename(file_path))[0]

def python_files(directory):
    return glob.glob(os.path.join(directory, "*.py"))

def manual_start(mb, file_path, file_name):
    with open(file_path, "r") as f:
        code = f.read()
    p = subprocess.Popen(args=["python", "-"], stdin=subprocess.PIPE)
    p.stdin.write(code)
    p.stdin.close()

def start(mb, file_path, file_name):
    with open(file_path, "r") as f:
        code = f.read()
    mb.post(key="start_process", content={'name':file_name, 'code':code})

def start_and_check(mb, file_path, starter):
    file_name = basename_without_extension(file_path)
    ready_key = 'process_ready.%s' % file_name
    queue = mb.watch_for(keys=[ready_key])
    starter(mb, file_path, file_name)
    message = mb.get_one_message(queue)
    return message and ready_key == message.key

def bootstrap_start(mb, name, starter, test_key):
    file_paths = glob.glob(os.path.join('bootstrap', '%s*.py' % name))
    for file_path in file_paths:
        if not start_and_check(mb, file_path, starter):
            return False

    return mb.post_and_check(post_key='component_ready.%s' % name, response_key=test_key, response_content=True)

def start_component(mb, name, directory):
    for file_path in python_files(directory):
        if not start_and_check(mb, file_path, starter=start):
            return False
    return True

def start_components(mb, directories):
    for directory in directories:
        name = os.path.basename(directory)
        if start_component(mb, name, directory):
            mb.post(key='component_ready.%s' % name)
        else:
            mb.post(key='component_failed.%s' % name)

component_directories = sys.argv[1:]
mb = messageboard.MessageBoard()

if not bootstrap_start(mb, name='process_starter', starter=manual_start, test_key='process_starter_test_result'):
    mb.post(key="bootstrap_failed")
    exit()

start_components(mb, component_directories)

mb.post(key="bootstrap_finished")
while 1:
    pass
