#!/usr/bin/ruby
require 'net/http'
require 'json'

def store_fact(factspace, type, content)
  store_statement('fact', factspace, type, content)
end

def store_opinion(factspace, type, content)
  store_statement('opinion', factspace, type, content)
end

def store_statement(confidence, factspace, type, content)
  kropotkin_url = ENV['KROPOTKIN_URL']
  url = '%s/factspace/%s/%s/%s' % [kropotkin_url, factspace, confidence, type]
  uri = URI.parse(url)
  http = Net::HTTP.new(uri.host, uri.port)
  resp = http.post(url, JSON.dump(content))
  return (resp.code == '200')
end
